name: VirusTotal Check

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: 8897459540
        path: .
        github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
        merge-multiple: true
    - name: Display structure of downloaded files
      run: ls -R .

  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: Display structure of downloaded files
        run: ls -R .
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            *.exe
